/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_code_jnitest_AndroidJni */

#ifndef _Included_com_code_jnitest_AndroidJni
#define _Included_com_code_jnitest_AndroidJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_code_jnitest_AndroidJni
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_code_jnitest_AndroidJni_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_code_jnitest_AndroidJni
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_code_jnitest_AndroidJni_plus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
